name: Maven Tests with JaCoCo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@3.14.1
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and run tests with JaCoCo
        run: mvn clean verify

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@4.6.2
        with:
          name: jacoco-report
          path: target/site/jacoco
