name: Maven Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@3.14.1
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build without tests, force UTF-8 encoding
        run: mvn clean package -DskipTests -Dfile.encoding=UTF-8
